export type SpeciesInfo = {
  Scientific_Name: string;
  Category: string;
  Hebrew_Name: string;
  English_Name: string;
};

const rawSpeciesMap = {
  "פרפרים": [
    { "scientific_name": "Euchloe aegyptiaca", "hebrew_name": "ירוק־כנף מצרי", "english_name": "" },
    { "scientific_name": "Euchloe falloui", "hebrew_name": "ירוק-כנף המוריקה", "english_name": "" },
    { "scientific_name": "Allancastria deyrollei", "hebrew_name": "צבעוני צהבהב", "english_name": "" },
    { "scientific_name": "Zerynthia cerisy", "hebrew_name": "צבעוני קשוט", "english_name": "" },
    { "scientific_name": "Elphinstonia charlonia", "hebrew_name": "ירוק-כנף צהבהב", "english_name": "" },
    { "scientific_name": "Cigaritis cilissa", "hebrew_name": "נחושתן-נמלים גלילי", "english_name": "" },
    { "scientific_name": "Borbo borbonica", "hebrew_name": "הספרית ביצות", "english_name": "Zeller's Skipper" },
    { "scientific_name": "Belenois aurota", "hebrew_name": "לבנין משויש", "english_name": "" },
    { "scientific_name": "Gegenes nostrodamus", "hebrew_name": "הספרית עשב", "english_name": "" },
    { "scientific_name": "Hypolimnas misippus", "hebrew_name": "נימפית הרגלה", "english_name": "" },
    { "scientific_name": "Hyponephele lupinus", "hebrew_name": "סטירית סומית", "english_name": "" },
    { "scientific_name": "Papilio saharae", "hebrew_name": "זנב-סנונית מדברי", "english_name": "" },
    { "scientific_name": "Turanana panagea", "hebrew_name": "תכול-כנף נקוד", "english_name": "" },
    { "scientific_name": "Iolaus glaucus", "hebrew_name": "תכלתן ההרנוג", "english_name": "" },
    { "scientific_name": "Junonia hierta", "hebrew_name": "נימפית הריסן", "english_name": "" },
    { "scientific_name": "Polyommatus eurypilus", "hebrew_name": "כחליל הכרבולת", "english_name": "" },
    { "scientific_name": "Cigaritis acamas", "hebrew_name": "נחושתן-נמלים מפוספס", "english_name": "" },
    { "scientific_name": "Luthrodes galba", "hebrew_name": "כחליל הקטנית", "english_name": "" },
    { "scientific_name": "Quercusia quercus", "hebrew_name": "אלוני סגול", "english_name": "" },
    { "scientific_name": "Callophrys rubi", "hebrew_name": "ירוקי אירופי", "english_name": "" },
    { "scientific_name": "Polyommatus juno", "hebrew_name": "כחליל החרמון", "english_name": "" },
    { "scientific_name": "Plebejus loewii", "hebrew_name": "כחליל לואי", "english_name": "" },
    { "scientific_name": "Kretania nichollae", "hebrew_name": "כחליל ניקול", "english_name": "" },
    { "scientific_name": "Cyaniris semiargus", "hebrew_name": "כחליל חינני", "english_name": "" },
    { "scientific_name": "Plebejus cleopatra", "hebrew_name": "כחליל קלאופטרה", "english_name": "" },
    { "scientific_name": "Plebeius philbyi", "hebrew_name": "כחליל ערבתי", "english_name": "" },
    { "scientific_name": "Luthrodes pandava", "hebrew_name": "כחליל הציקס", "english_name": "" },
    { "scientific_name": "Aricia crassipuncta", "hebrew_name": "כחליל מאפיר", "english_name": "" },
    { "scientific_name": "Tarucus rosacea", "hebrew_name": "כחלון השיזף", "english_name": "" },
    { "scientific_name": "Anthocharis gruneri", "hebrew_name": "כתום-כנף הדו-פרית", "english_name": "" },
    { "scientific_name": "Anthocharis damone", "hebrew_name": "כתום-כנף צהוב", "english_name": "" },
    { "scientific_name": "Pieris napi", "hebrew_name": "לבנין מעורק", "english_name": "" },
    { "scientific_name": "Colias aurorina", "hebrew_name": "צהבוני הלבנון", "english_name": "" },
    { "scientific_name": "Hesperia nomas", "hebrew_name": "אפורית מלבינה", "english_name": "" },
    { "scientific_name": "Muschampia proteides lycaonius", "hebrew_name": "אפורית חלודית", "english_name": "" },
    { "scientific_name": "Muschampia proto", "hebrew_name": "אפורית אירופית", "english_name": "" },
    { "scientific_name": "Melitaea arduinna", "hebrew_name": "כתמית הדרדר", "english_name": "" },
    { "scientific_name": "Melitaea deserticola", "hebrew_name": "כתמית מדברית", "english_name": "" },
    { "scientific_name": "Melitaea collina", "hebrew_name": "כתמית צפונית", "english_name": "" },
    { "scientific_name": "Carcharodus orientalis", "hebrew_name": "אפורית המכבים", "english_name": "" },
    { "scientific_name": "Thymelicus acteon", "hebrew_name": "נחושת השעורה", "english_name": "" },
    { "scientific_name": "Thymelicus hyrax", "hebrew_name": "נחושה נאה", "english_name": "" },
    { "scientific_name": "Aglais urticae", "hebrew_name": "נימפית החרמון", "english_name": "" },
    { "scientific_name": "Thymelicus lineola", "hebrew_name": "נחושת החיטה", "english_name": "" },
    { "scientific_name": "Fabriciana niobe", "hebrew_name": "כתמית הסיגל", "english_name": "" },
    { "scientific_name": "Carcharodus stauderi", "hebrew_name": "אפורית הגלונית", "english_name": "" },
    { "scientific_name": "Nymphalis polychloros", "hebrew_name": "נימפית מגוונת", "english_name": "" },
    { "scientific_name": "Satyrus ferula", "hebrew_name": "סטירית מפויחת", "english_name": "" },
    { "scientific_name": "Pyrgus serratulae", "hebrew_name": "אפורית החמשן", "english_name": "" },
    { "scientific_name": "Pseudochazara thelephassa", "hebrew_name": "סטירית מערות", "english_name": "" },
    { "scientific_name": "Elphinstonia penia", "hebrew_name": "ירוק-כנף המנתור", "english_name": "" },
    { "scientific_name": "Anthene amarah", "hebrew_name": "שיטן אילתי", "english_name": "" },
    { "scientific_name": "Aricia isaurica", "hebrew_name": "כחליל חיוור", "english_name": "" },
    { "scientific_name": "Gomalia elma", "hebrew_name": "אפורית האבוטילון", "english_name": "" },
    { "scientific_name": "Polygonia c-album", "hebrew_name": "נימפית טוביה", "english_name": "" },
    { "scientific_name": "Colias croceus", "hebrew_name": "צהבוני התלתן", "english_name": "" },
    { "scientific_name": "Limenitis reducta", "hebrew_name": "אצילית היערה", "english_name": "" },
    { "scientific_name": "Papilio machaon", "hebrew_name": "זנב סנונית נאה", "english_name": "" },
    { "scientific_name": "Papilio demoleus", "hebrew_name": "זנב סנונית הלימון", "english_name": "Lime Butterfly" },
    { "scientific_name": "Papilio alexanor", "hebrew_name": "זנב סנונית המכבים", "english_name": "" },
    { "scientific_name": "Pararge aegeria", "hebrew_name": "חומית מנומרת", "english_name": "" },
    { "scientific_name": "Hesperia comma", "hebrew_name": "נחושה לבנת-כתמים", "english_name": "" },
    { "scientific_name": "Thymelicus sylvestris", "hebrew_name": "נחושת הנשרן", "english_name": "" },
    { "scientific_name": "Lycaena", "hebrew_name": "נחושתן זהוב", "english_name": "" },
    { "scientific_name": "Lycaena phlaeas", "hebrew_name": "נחושתן הארכובית", "english_name": "" },
    { "scientific_name": "Spialia phlomidis", "hebrew_name": "נקדית החרמון", "english_name": "" },
    { "scientific_name": "Spialia sertorius", "hebrew_name": "נקדית הורדיים", "english_name": "" },
    { "scientific_name": "Vanessa cardui", "hebrew_name": "נימפית החורשף", "english_name": "" },
    { "scientific_name": "Vanessa atalanta", "hebrew_name": "נמפית הסרפד", "english_name": "" },
    { "scientific_name": "Melitaea cinxia", "hebrew_name": "כתמית הוורוניקה", "english_name": "" },
    { "scientific_name": "Melitaea trivia", "hebrew_name": "כתמית הבוצין", "english_name": "" },
    { "scientific_name": "Damora pandora", "hebrew_name": "כתמית פנדורה", "english_name": "" },
    { "scientific_name": "Melitaea telona", "hebrew_name": "כיתמית אריאל", "english_name": "" },
    { "scientific_name": "Spialia doris", "hebrew_name": "נקדית החבלבל", "english_name": "" },
    { "scientific_name": "Iphiclides podalirius", "hebrew_name": "סנוניתן הוורדיים", "english_name": "" },
    { "scientific_name": "Lasiommata maera", "hebrew_name": "חומית היבלית", "english_name": "" },
    { "scientific_name": "Pseudochazara pelopea", "hebrew_name": "סטירית חרמונית", "english_name": "" },
    { "scientific_name": "Hyponephele lycaon", "hebrew_name": "סטירית חיוורת", "english_name": "" },
    { "scientific_name": "Chazara persephone", "hebrew_name": "סטירית טלואה", "english_name": "" },
    { "scientific_name": "Lasiommata megera", "hebrew_name": "חומית הציבורת", "english_name": "" },
    { "scientific_name": "Hipparchia fatua", "hebrew_name": "סטירית אפלה", "english_name": "" },
    { "scientific_name": "Maniola telmessia", "hebrew_name": "סטירית פקוחה", "english_name": "" },
    { "scientific_name": "Zerynthia deyrollei", "hebrew_name": "צבעוני צהוב", "english_name": "" },
    { "scientific_name": "Archon apollinus", "hebrew_name": "צבעון שקוף", "english_name": "" },
    { "scientific_name": "Tomares nesimachus", "hebrew_name": "צמריר הקדד", "english_name": "" },
    { "scientific_name": "Aporia crataegi", "hebrew_name": "רשתן העוזרר", "english_name": "" },
    { "scientific_name": "Danaus chrysippus", "hebrew_name": "דנאית הדורה", "english_name": "" },
    { "scientific_name": "Colotis fausta", "hebrew_name": "דרומי הצלף", "english_name": "" },
    { "scientific_name": "Pelopidas thrax", "hebrew_name": "הספרית הדוחן", "english_name": "" },
    { "scientific_name": "Gegenes pumilio", "hebrew_name": "הספרית שחורה", "english_name": "" },
    { "scientific_name": "Catopsilia florella", "hebrew_name": "הגרן הסנא", "english_name": "" },
    { "scientific_name": "Tarucus balkanica", "hebrew_name": "כחלון הבלקן", "english_name": "" },
    { "scientific_name": "Cacyreus marshalli", "hebrew_name": "כחלון הפלרגון", "english_name": "" },
    { "scientific_name": "Azanus ubaldus", "hebrew_name": "כחלון השיטה", "english_name": "" },
    { "scientific_name": "Leptotes pirithous", "hebrew_name": "כחלון האספסת", "english_name": "" },
    { "scientific_name": "Thersamonia thersamon", "hebrew_name": "נחושתן החומעה", "english_name": "" },
    { "scientific_name": "Lampides boeticus", "hebrew_name": "כחלון האפון", "english_name": "" },
    { "scientific_name": "Plebejus amanda", "hebrew_name": "כחליל הבקיה", "english_name": "" },
    { "scientific_name": "Zizeeria karsandra", "hebrew_name": "כחלון הקוטב", "english_name": "" },
    { "scientific_name": "Polyommatus icarus", "hebrew_name": "כחליל השברק", "english_name": "" },
    { "scientific_name": "Pseudophilotes baton", "hebrew_name": "תכליל האזוב", "english_name": "" },
    { "scientific_name": "Nordmannia ilicis", "hebrew_name": "שעיר האלון", "english_name": "" },
    { "scientific_name": "Plebejidea loewi", "hebrew_name": "כחליל המדבר", "english_name": "" },
    { "scientific_name": "Azanus jesous", "hebrew_name": "כחלון הינבוט", "english_name": "" },
    { "scientific_name": "Lycaena asabinus", "hebrew_name": "נחושתן מזרחי", "english_name": "" },
    { "scientific_name": "Anthocharis cardamines", "hebrew_name": "כתום-כנף המצילתיים", "english_name": "" },
    { "scientific_name": "Melitaea acentria", "hebrew_name": "כתמית החרמון", "english_name": "" },
    { "scientific_name": "Melitaea didyma", "hebrew_name": "כתמית הלבנון", "english_name": "" },
    { "scientific_name": "Issoria lathonia", "hebrew_name": "כתמית פנינים", "english_name": "" },
    { "scientific_name": "Celastrina argiolus", "hebrew_name": "תכול-כנף קיסוסי", "english_name": "" },
    { "scientific_name": "Iolana alfierii", "hebrew_name": "קרקשי הסנה", "english_name": "" },
    { "scientific_name": "Satyrium myrtale", "hebrew_name": "שעיר הדובדבן", "english_name": "" },
    { "scientific_name": "Satyrium abdominalis", "hebrew_name": "שעיר השקד", "english_name": "" },
    { "scientific_name": "Tuttiola spini", "hebrew_name": "שעיר האשחר", "english_name": "" },
    { "scientific_name": "Parnassius mnemosyne", "hebrew_name": "שילגן חרמוני", "english_name": "" },
    { "scientific_name": "Melanargia titea", "hebrew_name": "אביבית משויישת", "english_name": "" },
    { "scientific_name": "Carcharodus alceae", "hebrew_name": "אפורית החלמית", "english_name": "" },
    { "scientific_name": "Erynnis marloyi", "hebrew_name": "אפורית אפלולית", "english_name": "" },
    { "scientific_name": "Colotis phisadia", "hebrew_name": "דרומי הסלודורה", "english_name": "" },
    { "scientific_name": "Pieris rapae", "hebrew_name": "לבנין הצנון", "english_name": "" },
    { "scientific_name": "Pontia daplidice", "hebrew_name": "לבנין הרכפה", "english_name": "" },
    { "scientific_name": "Pontia glauconome", "hebrew_name": "לבנין הרכפתן", "english_name": "" },
    { "scientific_name": "Pieris brassicae", "hebrew_name": "לבנין הכרוב", "english_name": "" },
    { "scientific_name": "Euchloe ausonia", "hebrew_name": "ירוק-כנף טלוא", "english_name": "" },
    { "scientific_name": "Euchloe belemia", "hebrew_name": "ירוק-כנף מפוספס", "english_name": "" },
    { "scientific_name": "Gonepteryx cleopatra", "hebrew_name": "לימוני האשחר", "english_name": "" },
    { "scientific_name": "Gonepteryx rhamni", "hebrew_name": "לימוני אירופי", "english_name": "" },
    { "scientific_name": "Gonepteryx farinosa", "hebrew_name": "לימונית החרמון", "english_name": "" },
    { "scientific_name": "Pyrgus melotis", "hebrew_name": "אפורית מזרחית", "english_name": "" },
    { "scientific_name": "Junonia orithya", "hebrew_name": "נימפית כחולה", "english_name": "" },
    { "scientific_name": "Aricia agestis", "hebrew_name": "כחליל הגרניון", "english_name": "" },
    { "scientific_name": "Ypthima asterope", "hebrew_name": "טבעית זוטית", "english_name": "" },
    { "scientific_name": "Hipparchia pisidice", "hebrew_name": "סטירית סיני", "english_name": "" },
    { "scientific_name": "Pseudophilotes abencerragus", "hebrew_name": "תכליל נבטי", "english_name": "" },
    { "scientific_name": "Freyeria trochylus", "hebrew_name": "כחליל מקושט", "english_name": "" },
    { "scientific_name": "Glaucopsyche alexis", "hebrew_name": "כחליל הדבשה", "english_name": "" },
    { "scientific_name": "Melitaea phoebe", "hebrew_name": "כתמית אירופית", "english_name": "" },
    { "scientific_name": "Kirinia roxelana", "hebrew_name": "חומנית עינונית", "english_name": "" },
    { "scientific_name": "Maniola jurtina", "hebrew_name": "סטירית הקיץ", "english_name": "" },
    { "scientific_name": "Catopsilia pyranthe", "hebrew_name": "Mottled Emigrant", "english_name": "" },
    { "scientific_name": "Melitaea persea", "hebrew_name": "נימפית פרסית", "english_name": "" },
    { "scientific_name": "Deudorix livia", "hebrew_name": "כחליל הרימון", "english_name": "" },
    { "scientific_name": "Zegris eupheme", "hebrew_name": "כתום-קצה מדברי", "english_name": "" },
    { "scientific_name": "Polygonia egea", "hebrew_name": "נימפית משוננת", "english_name": "" },
    { "scientific_name": "Charaxes jasius", "hebrew_name": "קיסרית הקטלב", "english_name": "" },
    { "scientific_name": "Brephidium exilis", "hebrew_name": "Western Pygmy-Blue", "english_name": "" },
    { "scientific_name": "Philareta treitschkii", "hebrew_name": "פילרטה טרייטשקיי", "english_name": "" },
    { "scientific_name": "Colotis chrysonome", "hebrew_name": "דרומי המרואה", "english_name": "" }
  ],

  "שפיראים": [
    { "scientific_name": "Ischnura pumilio", "hebrew_name": "שלחית זעירה", "english_name": "Small Bluetail" },
    { "scientific_name": "Anax imperator", "hebrew_name": "חניתית היאור", "english_name": "Emperor Dragonfly" },
    { "scientific_name": "Crocothemis erythraea", "hebrew_name": "תכשיתית זוהרת", "english_name": "Broad Scarlet" },
    { "scientific_name": "Trithemis annulata", "hebrew_name": "גיחנית ארגמנית", "english_name": "Violet Dropwing" },
    { "scientific_name": "Platycnemis dealbata", "hebrew_name": "שפרירית הפלגים", "english_name": "Ivory Featherleg" },
    { "scientific_name": "Orthetrum chrysostigma", "hebrew_name": "שפירית כחולה", "english_name": "Epaulet Skimmer" },
    { "scientific_name": "Libellulidae", "hebrew_name": "שפיריתיים", "english_name": "Skimmers" },
    { "scientific_name": "Odonata", "hebrew_name": "שפיראים", "english_name": "Dragonflies" },
    { "scientific_name": "Aeshnidae", "hebrew_name": "נימפיתיים", "english_name": "Hawkers" }
  ],
  "עופות": [
    { "scientific_name": "Aves", "hebrew_name": "עופות", "english_name": "Birds" },
    { "scientific_name": "Acridotheres tristis", "hebrew_name": "מיינה הודית", "english_name": "Common Myna" },
    { "scientific_name": "Psittacula krameri", "hebrew_name": "דררה", "english_name": "Rose-ringed Parakeet" },
    { "scientific_name": "Myiopsitta monachus", "hebrew_name": "תוכי נזירי", "english_name": "Monk Parakeet" }
  ],
  "יונקים": [
    { "scientific_name": "Mammalia", "hebrew_name": "יונקים", "english_name": "Mammals" },
    { "scientific_name": "Myocastor coypus", "hebrew_name": "נוטריה", "english_name": "Coypu" },
    { "scientific_name": "Felis chaus", "hebrew_name": "חתול ביצות", "english_name": "Jungle Cat" },
    { "scientific_name": "Lutra lutra", "hebrew_name": "לוטרה", "english_name": "Eurasian Otter" }
  ],
  "חרקים אחרים": [
    { "scientific_name": "Earias insulana", "hebrew_name": "זיפית הכותנה", "english_name": "" },
    { "scientific_name": "Zeuzera pyrina", "hebrew_name": "ססעץ מנומר", "english_name": "" },
    { "scientific_name": "Oiketicoides jordana", "hebrew_name": "ססתיק פרוע", "english_name": "" },
    { "scientific_name": "Phalacropterix bruandi", "hebrew_name": "ססתיק שחור-חזה", "english_name": "" },
    { "scientific_name": "Zygaena olivieri", "hebrew_name": "ססמבריק הלבנון", "english_name": "" },
    { "scientific_name": "Zygaena graslini", "hebrew_name": "ססמבריק אדמוני", "english_name": "" },
    { "scientific_name": "Acherontia atropos", "hebrew_name": "רפרף גולגולת המת", "english_name": "" },
    { "scientific_name": "Agrius convolvuli", "hebrew_name": "רפרף החבלבל", "english_name": "" },
    { "scientific_name": "Theretra alecto", "hebrew_name": "רפרף הגפן", "english_name": "" },
    { "scientific_name": "Macroglossum stellatarum", "hebrew_name": "רפרף הדבקה", "english_name": "" },
    { "scientific_name": "Daphnis nerii", "hebrew_name": "רפרף ההרדוף", "english_name": "" },
    { "scientific_name": "Marumba quercus", "hebrew_name": "רפרף האלון", "english_name": "" },
    { "scientific_name": "Hippotion celerio", "hebrew_name": "רפרף כסוף-קו", "english_name": "" },
    { "scientific_name": "Hyles livornica", "hebrew_name": "רפרף מסורטט", "english_name": "" },
    { "scientific_name": "Phthorimaea absoluta", "hebrew_name": "עש מנהרות העגבנייה", "english_name": "" },
    { "scientific_name": "Thaumetopoea solitaria", "hebrew_name": "תהלוכן האלה", "english_name": "" },
    { "scientific_name": "Pachypasa otus", "hebrew_name": "טוואי הברוש", "english_name": "" },
    { "scientific_name": "Thaumetopoea processionea", "hebrew_name": "תהלוכן האלון", "english_name": "" },
    { "scientific_name": "Bufoidia ledereri", "hebrew_name": "טוואי אפרפר", "english_name": "" },
    { "scientific_name": "Orgyia dubia", "hebrew_name": "טוואית הארכובית", "english_name": "" },
    { "scientific_name": "Lasiocampa grandis", "hebrew_name": "טוואי גדול", "english_name": "" },
    { "scientific_name": "Amata mestralii", "hebrew_name": "ברדן בוהק", "english_name": "" },
    { "scientific_name": "Spodoptera cilium", "hebrew_name": "גדודנית הדגן", "english_name": "" },
    { "scientific_name": "Spodoptera littoralis", "hebrew_name": "גדודנית פרודניה", "english_name": "" },
    { "scientific_name": "Spodoptera exigua", "hebrew_name": "גדודנית לפיגמה", "english_name": "" },
    { "scientific_name": "Acherontia styx", "hebrew_name": "גולגולת-מת מזרחית", "english_name": "" },
    { "scientific_name": "Olepa ricini", "hebrew_name": "דובון הקיקיון", "english_name": "" },
    { "scientific_name": "Ocnogyna loewii", "hebrew_name": "דובון אביב", "english_name": "" },
    { "scientific_name": "Paidia cinerascens", "hebrew_name": "דובון אפרפר", "english_name": "" },
    { "scientific_name": "Cymbalophora oertzeni", "hebrew_name": "דובון מנומר", "english_name": "" },
    { "scientific_name": "Utetheisa pulchella", "hebrew_name": "דובון יפהפה", "english_name": "" },
    { "scientific_name": "Duponchelia fovealis", "hebrew_name": "עש הרקפת", "english_name": "" },
    { "scientific_name": "Phereoeca uterella", "hebrew_name": "עש הבית", "english_name": "" },
    { "scientific_name": "Cydia pomonella", "hebrew_name": "עש התפוח", "english_name": "" },
    { "scientific_name": "Thaumatotibia leucotreta", "hebrew_name": "עש התפוח המדומה", "english_name": "" },
    { "scientific_name": "Lobesia botrana", "hebrew_name": "עש האשכול", "english_name": "" },
    { "scientific_name": "Palpita vitrealis", "hebrew_name": "עש היסמין", "english_name": "" },
    { "scientific_name": "Ectomyelois ceratoniae", "hebrew_name": "עש החרוב", "english_name": "" },
    { "scientific_name": "Uresiphita gilvata", "hebrew_name": "עשנור הרותם", "english_name": "" },
    { "scientific_name": "Plodia interpunctella", "hebrew_name": "עש הקמח ההודי", "english_name": "" },
    { "scientific_name": "Plutella xylostella", "hebrew_name": "עשית המצליבים", "english_name": "" },
    { "scientific_name": "Chrysodeixis chalcites", "hebrew_name": "פלוסית זהובה", "english_name": "" },
    { "scientific_name": "Autographa gamma", "hebrew_name": "פלוסית גמה", "english_name": "" },
    { "scientific_name": "Cucullia calendulae", "hebrew_name": "תנשמית ציפורני חתול", "english_name": "" },
    { "scientific_name": "Acronicta rumicis", "hebrew_name": "תנשמית החומעה", "english_name": "" },
    { "scientific_name": "Catocala elocata", "hebrew_name": "תנשמית הצפצפה", "english_name": "" },
    { "scientific_name": "Olivenebula subsericata", "hebrew_name": "תנשמית העוזרר", "english_name": "" },
    { "scientific_name": "Helicoverpa armigera", "hebrew_name": "תנשמית האביב", "english_name": "" },
    { "scientific_name": "Heliothis peltigera", "hebrew_name": "תנשמית המורכבים", "english_name": "" },
    { "scientific_name": "Hypena lividalis", "hebrew_name": "תנשמית עשנורית", "english_name": "" },
    { "scientific_name": "Euchalcia paulina", "hebrew_name": "תנשמית פאולוס", "english_name": "" },
    { "scientific_name": "Episema tamardayanae", "hebrew_name": "תנשמית תמר", "english_name": "" },
    { "scientific_name": "Acronicta aceris", "hebrew_name": "תנשמית יהודה", "english_name": "" },
    { "scientific_name": "Thaumetopoea wilkinsoni", "hebrew_name": "תהלוכן האורן", "english_name": "" },
    { "scientific_name": "Saturnia pyri", "hebrew_name": "שבתאי השקד", "english_name": "" },
    { "scientific_name": "Agrotis segetum", "hebrew_name": "אגרוטיס השורשים", "english_name": "" },
    { "scientific_name": "Noctua pronuba", "hebrew_name": "אגרוטיס כתום", "english_name": "" },
    { "scientific_name": "Scopula luridata", "hebrew_name": "מודד צהוב", "english_name": "" },
    { "scientific_name": "Larentia clavaria", "hebrew_name": "מודד החלמית", "english_name": "" },
    { "scientific_name": "Proteuchloris neriaria", "hebrew_name": "מודד הבלקן", "english_name": "" },
    { "scientific_name": "Zamarada torrida", "hebrew_name": "מודד השיטים", "english_name": "" },
    { "scientific_name": "Rhodometra sacraria", "hebrew_name": "מודד הארכוביות", "english_name": "" },
    { "scientific_name": "Ascotis selenaria", "hebrew_name": "מודד האבוקדו", "english_name": "" },
    { "scientific_name": "Problepsis ocellata", "hebrew_name": "מודד עינוני", "english_name": "" },
    { "scientific_name": "Selidosema combustaria", "hebrew_name": "מודד פאולוס", "english_name": "" },
    { "scientific_name": "Apochima flabellaria", "hebrew_name": "מודד קיפודי", "english_name": "" },
    { "scientific_name": "Ctenoplusia accentifera", "hebrew_name": "קטנופלוסיה אקסנטיפרה", "english_name": "" },
    { "scientific_name": "Tathorhynchus exsiccata", "hebrew_name": "טאתורינכוס אקסיקטה", "english_name": "" },
    { "scientific_name": "Cadra cautella", "hebrew_name": "קדרה קאוטלה", "english_name": "" },
    { "scientific_name": "Phlogophora meticulosa", "hebrew_name": "פלוגופורה מטיקולוסה", "english_name": "" },
    { "scientific_name": "Agrochola lychnidis", "hebrew_name": "אגרוקולה ליכנידיס", "english_name": "" },
    { "scientific_name": "Amblyptilia acanthadactyla", "hebrew_name": "אמבליפטילייה אקנתדקטילה", "english_name": "" },
    { "scientific_name": "Loxostege sticticalis", "hebrew_name": "לוקסוסטגה סטיקטיקליס", "english_name": "" },
    { "scientific_name": "Aporophyla nigra", "hebrew_name": "אפורופילה ניגרה", "english_name": "" },
    { "scientific_name": "Garella nilotica", "hebrew_name": "גארלה נילוטיקה", "english_name": "" },
    { "scientific_name": "Cyclophora puppillaria", "hebrew_name": "ציקלופורה פופילריה", "english_name": "" },
    { "scientific_name": "Hypena obsitalis", "hebrew_name": "היפנה אובסיטליס", "english_name": "" },
    { "scientific_name": "Idaea ochrata", "hebrew_name": "אידאה אוכרטה", "english_name": "" },
    { "scientific_name": "Trichoplusia ni", "hebrew_name": "טריכופלוסיה ני", "english_name": "" },
    { "scientific_name": "Tinea pellionella", "hebrew_name": "טינאה פליונלה", "english_name": "" },
    { "scientific_name": "Atethmia centrago", "hebrew_name": "אתתמיה צנטראגו", "english_name": "" },
    { "scientific_name": "Cucullia chamomillae", "hebrew_name": "קוקוליה כממילה", "english_name": "" },
    { "scientific_name": "Bryotropha terrella", "hebrew_name": "בריוטרופה טרלה", "english_name": "" },
    { "scientific_name": "Phyllocnistis citrella", "hebrew_name": "פילוקניסטיס ציטרלה", "english_name": "" },
    { "scientific_name": "Hypsopygia costalis", "hebrew_name": "היפסופוגיה קוסטליס", "english_name": "" },
    { "scientific_name": "Gypsonoma dealbana", "hebrew_name": "גיפסונומה דיאלבנה", "english_name": "" },
    { "scientific_name": "Blastesthia tessulatana", "hebrew_name": "עשפרי הברוש", "english_name": "" },
    { "scientific_name": "Epicallia villica", "hebrew_name": "דובון החורש", "english_name": "" },
    { "scientific_name": "Agrotis trux", "hebrew_name": "אגרוטיס טרוקס", "english_name": "" },
    { "scientific_name": "Leucania putrescens", "hebrew_name": "לוקניה פוטרסנס", "english_name": "" },
    { "scientific_name": "Collita griseola", "hebrew_name": "איילמה גריסאולה", "english_name": "" },
    { "scientific_name": "Gymnoscelis rufifasciata", "hebrew_name": "גימנוסליס רופיפסיאטה", "english_name": "" },
    { "scientific_name": "Endothenia oblongana", "hebrew_name": "אנדותניה אובלונגנה", "english_name": "" },
    { "scientific_name": "Tephronia sepiaria", "hebrew_name": "טפרוניה ספיאריה", "english_name": "" },
    { "scientific_name": "Heliothis nubigera", "hebrew_name": "הליאוטיס נוביגרה", "english_name": "" },
    { "scientific_name": "Cornutiplusia circumflexa", "hebrew_name": "קורנוטיפלוסיה סירקומפלקסה", "english_name": "" },
    { "scientific_name": "Ostrinia nubilalis", "hebrew_name": "נובר התירס האירופי", "english_name": "" },
    { "scientific_name": "Tyta luctuosa", "hebrew_name": "טיטה לוקטואוסה", "english_name": "" },
    { "scientific_name": "Oegoconia quadripuncta", "hebrew_name": "אגוקוניה מרובעת", "english_name": "" },
    { "scientific_name": "Xanthorhoe fluctuata", "hebrew_name": "קסנתורה פלוקטטה", "english_name": "" },
    { "scientific_name": "Anania verbascalis", "hebrew_name": "אנניה ורבסקליס", "english_name": "" },
    { "scientific_name": "Herpetogramma licarsisalis", "hebrew_name": "הרפטוגרמה ליקרסיסליס", "english_name": "" },
    { "scientific_name": "Agrotis bigramma", "hebrew_name": "אגרוטיס ביגרמה", "english_name": "" },
    { "scientific_name": "Galleria mellonella", "hebrew_name": "עש השעווה הגדול", "english_name": "" },
    { "scientific_name": "Ophiusa tirhaca", "hebrew_name": "אופיוסה טירקא", "english_name": "" },
    { "scientific_name": "Adscita statices", "hebrew_name": "אדסקיטה סטטיקס", "english_name": "" },
    { "scientific_name": "Agrotis spinifera", "hebrew_name": "אגרוטיס ספיניפרה", "english_name": "" },
    { "scientific_name": "Agrotis catalaunensis", "hebrew_name": "אגרוטיס קטלאוננסיס", "english_name": "" },
    { "scientific_name": "Spoladea recurvalis", "hebrew_name": "ספולאדאה רקורבליס", "english_name": "" },
    { "scientific_name": "Nemophora fasciella", "hebrew_name": "נמופורה פסיאלה", "english_name": "" },
    { "scientific_name": "Pyrausta testalis", "hebrew_name": "הודברטיה טסטליס", "english_name": "" },
    { "scientific_name": "Acanthovalva inconspicuaria", "hebrew_name": "אקנתובלבה אינקונספיקואריה", "english_name": "" },
    { "scientific_name": "Agrotis ipsilon", "hebrew_name": "אגרוטיס איפסילון", "english_name": "" },
    { "scientific_name": "Pseudoterpna coronillaria", "hebrew_name": "פסאודוטרפנה קורונילריה", "english_name": "" },
    { "scientific_name": "Euplagia quadripunctaria", "hebrew_name": "יופלגיה קוואדריפונקטריה", "english_name": "" },
    { "scientific_name": "Dysgonia torrida", "hebrew_name": "דיסגוניה טוררידה", "english_name": "" },
    { "scientific_name": "Lantanophaga pusillidactylus", "hebrew_name": "לנטנופגה פוסילדקטילוס", "english_name": "" },
    { "scientific_name": "Batia lunaris", "hebrew_name": "בטיה לונריס", "english_name": "" },
    { "scientific_name": "Achroia grisella", "hebrew_name": "עש הדונג הקטן", "english_name": "" },
    { "scientific_name": "Agrotis cinerea", "hebrew_name": "אגרוטיס סינראיה", "english_name": "" },
    { "scientific_name": "Eupithecia centaureata", "hebrew_name": "אופיטסיה צנטאוראטה", "english_name": "" },
    { "scientific_name": "Cydia splendana", "hebrew_name": "צידיה ספלנדנה", "english_name": "" },
    { "scientific_name": "Pyralis farinalis", "hebrew_name": "עש הקמח", "english_name": "" },
    { "scientific_name": "Pyrausta aurata", "hebrew_name": "פיראוסטה אורטה", "english_name": "" },
    { "scientific_name": "Emmelina monodactyla", "hebrew_name": "עשנוצית החבלבל", "english_name": "" },
    { "scientific_name": "Cucullia verbasci", "hebrew_name": "תנשמית הבוצין", "english_name": "" },
    { "scientific_name": "Hellula undalis", "hebrew_name": "הלולה אונדליס", "english_name": "" },
    { "scientific_name": "Peribatodes umbraria", "hebrew_name": "פריבטודס אומברריה", "english_name": "" },
    { "scientific_name": "Achyra nudalis", "hebrew_name": "אכירה נודליס", "english_name": "" },
    { "scientific_name": "Spodoptera litura", "hebrew_name": "ספודופטרה ליטורה", "english_name": "" },
    { "scientific_name": "Hydriris ornatalis", "hebrew_name": "הידריריס אורנטליס", "english_name": "" },
    { "scientific_name": "Acontia lucida", "hebrew_name": "אקונטיה לוסידה", "english_name": "" },
    { "scientific_name": "Chloantha hyperici", "hebrew_name": "כלאונתה היפריסי", "english_name": "" },
    { "scientific_name": "Anarsia lineatella", "hebrew_name": "אנרסיה ליניאטלה", "english_name": "" },
    { "scientific_name": "Eublemma cochylioides", "hebrew_name": "אובלמה קוכילואידס", "english_name": "" },
    { "scientific_name": "Pechipogo plumigeralis", "hebrew_name": "Plumed Fan-foot", "english_name": "" },
    { "scientific_name": "Idaea degeneraria", "hebrew_name": "Portland Ribbon Wave", "english_name": "" },
    { "scientific_name": "Phragmataecia castaneae", "hebrew_name": "ססעץ הקנים", "english_name": "" },
    { "scientific_name": "Isturgia exerraria", "hebrew_name": "איסטורגיה אקסרריה", "english_name": "" },
    { "scientific_name": "Endotricha flammealis", "hebrew_name": "אנדוטריכה פלממליס", "english_name": "" },
    { "scientific_name": "Oncocera semirubella", "hebrew_name": "אונקוצרה סמירובלה", "english_name": "" },
    { "scientific_name": "Phragmatobia fuliginosa", "hebrew_name": "פרגמטובייה פוליגינוזה", "english_name": "" },
    { "scientific_name": "Nomophila noctuella", "hebrew_name": "נומופילה נוקטואלה", "english_name": "" },
    { "scientific_name": "Udea ferrugalis", "hebrew_name": "אודאה פרוגינליס", "english_name": "" },
    { "scientific_name": "Idaea inquinata", "hebrew_name": "אידאה אינקווינאטה", "english_name": "" },
    { "scientific_name": "Idaea subsericeata", "hebrew_name": "אידאה סובסריקטטה", "english_name": "" },
    { "scientific_name": "Pyrausta sanguinalis", "hebrew_name": "פיראוסטה סנגווינליס", "english_name": "" },
    { "scientific_name": "Antigastra catalaunalis", "hebrew_name": "אנטיגסטרה קטלאונליס", "english_name": "" },
    { "scientific_name": "Agrotis puta", "hebrew_name": "אגרוטיס פוטה", "english_name": "" },
    { "scientific_name": "Thysanoplusia orichalcea", "hebrew_name": "טיסנופלוסיה אוריכלקאה", "english_name": "" },
    { "scientific_name": "Scopula imitaria", "hebrew_name": "סקופולה אימיטריה", "english_name": "" },
    { "scientific_name": "Eublemma parva", "hebrew_name": "אובלמה קטנה", "english_name": "" },
    { "scientific_name": "Agrotis herzogi", "hebrew_name": "אגרוטיס הרצוגי", "english_name": "" },
    { "scientific_name": "Earias biplaga", "hebrew_name": "איאריס ביפלגה", "english_name": "" },
    { "scientific_name": "Lymantria dispar", "hebrew_name": "טוואית האלון", "english_name": "" },
    { "scientific_name": "Acontia trabealis", "hebrew_name": "אקונטיה טרבאליס", "english_name": "" },
    { "scientific_name": "Phyllonorycter blancardella", "hebrew_name": "פילונוריקטר בלנקארדלה", "english_name": "" },
    { "scientific_name": "Xestia xanthographa", "hebrew_name": "קססטיה קסנתוגרפה", "english_name": "" },
    { "scientific_name": "Cynaeda dentalis", "hebrew_name": "צינאדה דנטליס", "english_name": "" },
    { "scientific_name": "Aglossa caprealis", "hebrew_name": "אגלוסה קפריאליס", "english_name": "" },
    { "scientific_name": "Vittaplusia vittata", "hebrew_name": "ויטאפלוסיה ויטאטה", "english_name": "" },
    { "scientific_name": "Esperia sulphurella", "hebrew_name": "אספריה סולפורלה", "english_name": "" },
    { "scientific_name": "Chiasmia aestimaria", "hebrew_name": "כיאסמיה אסטימריה", "english_name": "" },
    { "scientific_name": "Eutelia adulatrix", "hebrew_name": "אאוטליה אדולטריקס", "english_name": "" },
    { "scientific_name": "Leucania loreyi", "hebrew_name": "לוקניה לוריי", "english_name": "" },
    { "scientific_name": "Dysgonia algira", "hebrew_name": "דיסגוניה אלגירה", "english_name": "" },
    { "scientific_name": "Lamoria anella", "hebrew_name": "עשנור התפוח", "english_name": "" },
    { "scientific_name": "Myelois circumvoluta", "hebrew_name": "מיילואיס סירקומבולוטה", "english_name": "" },
    { "scientific_name": "Pyralis manihotalis", "hebrew_name": "פירליס מניהוטליס", "english_name": "" },
    { "scientific_name": "Grammodes bifasciata", "hebrew_name": "גרמוודס ביפסיאטה", "english_name": "" },
    { "scientific_name": "Pseudozarba bipartita", "hebrew_name": "פסאודוזרבה ביפרטיטה", "english_name": "" },
    { "scientific_name": "Synclera traducalis", "hebrew_name": "סינקלרה טרדוקליס", "english_name": "" },
    { "scientific_name": "Ethmia bipunctella", "hebrew_name": "אתמיה ביפונקטלה", "english_name": "" },
    { "scientific_name": "Mythimna unipuncta", "hebrew_name": "מיתימנה יוניפונקטה", "english_name": "" },
    { "scientific_name": "Peribatodes rhomboidaria", "hebrew_name": "פריבטודס רומבוידריה", "english_name": "" },
    { "scientific_name": "Aspitates ochrearia", "hebrew_name": "אספיטטס אוקרריה", "english_name": "" },
    { "scientific_name": "Achlya flavicornis", "hebrew_name": "אכליה פלביקורניס", "english_name": "" },
    { "scientific_name": "Evergestis isatidalis", "hebrew_name": "אברגסטיס איסאטידליס", "english_name": "" },
    { "scientific_name": "Aglossa aglossalis", "hebrew_name": "אגלוסה אגלוסליס", "english_name": "" },
    { "scientific_name": "Agrotis pierreti", "hebrew_name": "אגרוטיס פיירטי", "english_name": "" },
    { "scientific_name": "Agriphila beieri", "hebrew_name": "אגריפילה ביירי", "english_name": "" },
    { "scientific_name": "Eublemma siticuosa", "hebrew_name": "אובלמה אלבינה", "english_name": "" },
    { "scientific_name": "Odites kollarella", "hebrew_name": "אודיטס קולרלה", "english_name": "" },
    { "scientific_name": "Euzophera osseatella", "hebrew_name": "אוזופרה אוסאטלה", "english_name": "" },
    { "scientific_name": "Euzophera lunulella", "hebrew_name": "אוזופרה לונוללה", "english_name": "" },
    { "scientific_name": "Oiketicoides lutea", "hebrew_name": "ססתיק צהוב", "english_name": "" },
    { "scientific_name": "Euchromius bella", "hebrew_name": "אוכרומיוס בלה", "english_name": "" },
    { "scientific_name": "Euchromius superbella", "hebrew_name": "אוכרומיוס סופרבלוס", "english_name": "" },
    { "scientific_name": "Euchromius cambridgei", "hebrew_name": "אאוכרומיוס קמברידג`אי", "english_name": "" },
    { "scientific_name": "Euchromius ramburiellus", "hebrew_name": "אוכרומיוס רמבוריאלוס", "english_name": "" },
    { "scientific_name": "Eumannia fumosata", "hebrew_name": "אומניה פומוסטה", "english_name": "" },
    { "scientific_name": "Eumera turcosyrica", "hebrew_name": "אומרה טורקוסוריקה", "english_name": "" },
    { "scientific_name": "Usgentia vespertalis", "hebrew_name": "אוסגנטיה וספרטליס", "english_name": "" },
    { "scientific_name": "Eupithecia extremata", "hebrew_name": "אופיטסיה אקסטרמטה", "english_name": "" },
    { "scientific_name": "Eupithecia syriacata", "hebrew_name": "אופיטסיה סיריאקטה", "english_name": "" },
    { "scientific_name": "Earias syriacana", "hebrew_name": "איאריס סיריאקנה", "english_name": "" },
    { "scientific_name": "Idaea intermedia", "hebrew_name": "אידאה אינטרמדיה", "english_name": "" },
    { "scientific_name": "Idaea infirmaria", "hebrew_name": "אידאה אינפרמריה", "english_name": "" },
    { "scientific_name": "Idaea inclinata", "hebrew_name": "אידאה אינקלינטה", "english_name": "" },
    { "scientific_name": "Idaea affinitata", "hebrew_name": "אידאה אפיניטטה", "english_name": "" },
    { "scientific_name": "Idaea distinctaria", "hebrew_name": "אידאה דיסטינקטריה", "english_name": "" },
    { "scientific_name": "Idaea longaria", "hebrew_name": "אידאה לונגריה", "english_name": "" },
    { "scientific_name": "Idaea palaestinensis", "hebrew_name": "אידאה פלשתינאית", "english_name": "" },
    { "scientific_name": "Idaea consanguinaria", "hebrew_name": "אידאה קונסנגווינריה", "english_name": "" },
    { "scientific_name": "Muscula muscula", "hebrew_name": "איילמה מוסקולה", "english_name": "" },
    { "scientific_name": "Isturgia berytaria", "hebrew_name": "איסטורגיה בריטריה", "english_name": "" },
    { "scientific_name": "Isturgia disputaria", "hebrew_name": "איסטורגיה דיספוטריה", "english_name": "" },
    { "scientific_name": "Albarracina warionis", "hebrew_name": "טוואית השרביטן", "english_name": "" },
    { "scientific_name": "Alophia combustella", "hebrew_name": "אלופיה קומבוסטלה", "english_name": "" },
    { "scientific_name": "Ematheudes punctellus", "hebrew_name": "אמאתאודס פונקטלה", "english_name": "" },
    { "scientific_name": "Amblypalpis olivierella", "hebrew_name": "עשבחנין הכישור", "english_name": "" },
    { "scientific_name": "Amicta quadrangularis", "hebrew_name": "ססתיק מרובע", "english_name": "" },
    { "scientific_name": "Ancylosis convexella", "hebrew_name": "אנצילוזיס קונבקסה", "english_name": "" },
    { "scientific_name": "Ancylolomia palpella", "hebrew_name": "אנצילולומיה פלפלה", "english_name": "" },
    { "scientific_name": "Ancylolomia pectinatella", "hebrew_name": "אנצילולומיה פקטינטלוס", "english_name": "" },
    { "scientific_name": "Acidaliastis micra", "hebrew_name": "אסידאליאסטיס מיקרה", "english_name": "" },
    { "scientific_name": "Arenipses sabella", "hebrew_name": "אפומיה סבלה", "english_name": "" },
    { "scientific_name": "Aporodes floralis", "hebrew_name": "אפורודס פלורליס", "english_name": "" },
    { "scientific_name": "Aporophyla canescens", "hebrew_name": "אפורופילה קנסנס", "english_name": "" },
    { "scientific_name": "Episema glaucina", "hebrew_name": "אפיסמה גלאוסינה", "english_name": "" },
    { "scientific_name": "Epicallima icterinella", "hebrew_name": "אפיקלימה איקטרינלה", "english_name": "" },
    { "scientific_name": "Acrobasis glaucella", "hebrew_name": "אקרובסיס פלואלה", "english_name": "" },
    { "scientific_name": "Acrobasis romanella", "hebrew_name": "אקרובסיס רומנלה", "english_name": "" },
    { "scientific_name": "Acronicta pasiphae", "hebrew_name": "אקרוניקטה פסיפאה", "english_name": "" },
    { "scientific_name": "Atethmia ambusta", "hebrew_name": "אתתמיה אמבוסטה", "english_name": "" },
    { "scientific_name": "Boursinia discordans", "hebrew_name": "בורסיניה דיסקורדנס", "english_name": "" },
    { "scientific_name": "Bifascioides leucomelanella", "hebrew_name": "ביפסקיואידס לאוקומלנלה", "english_name": "" },
    { "scientific_name": "Bembecia stiziformis", "hebrew_name": "במבציה סטיזיפורמיס", "english_name": "" },
    { "scientific_name": "Bryophila tephrocharis", "hebrew_name": "בריופילה טפרוכאריס", "english_name": "" },
    { "scientific_name": "Bryophila rectilinea", "hebrew_name": "בריופילה רקטילינאה", "english_name": "" },
    { "scientific_name": "Brachyglossina purpureomarginata", "hebrew_name": "ברכיגלוסינה פורפוראומארגינטה", "english_name": "" },
    { "scientific_name": "Grammodes boisdeffrii", "hebrew_name": "גרמוודס בואסדפרי", "english_name": "" },
    { "scientific_name": "Dolicharthria bruguieralis", "hebrew_name": "דוליכארתריה ברוגייראליס", "english_name": "" },
    { "scientific_name": "Dolicharthria daralis", "hebrew_name": "דוליכארתריה דארליס", "english_name": "" },
    { "scientific_name": "Dattinia guttosalis", "hebrew_name": "דטיניה גוטוזליס", "english_name": "" },
    { "scientific_name": "Dysauxes punctata", "hebrew_name": "דיסאוקסס פמולה", "english_name": "" },
    { "scientific_name": "Gnophos sartata", "hebrew_name": "מודד אפלולי", "english_name": "" },
    { "scientific_name": "Dasycorsa modesta", "hebrew_name": "דסיקורסה מודסטה", "english_name": "" },
    { "scientific_name": "Hypotia corticalis", "hebrew_name": "היפוטיה קורטיקליס", "english_name": "" },
    { "scientific_name": "Watsonalla uncinula", "hebrew_name": "ווטסונלה אוניקולה", "english_name": "" },
    { "scientific_name": "Zebeeba falsalis", "hebrew_name": "זבבה פלסאליס", "english_name": "" },
    { "scientific_name": "Zygaena brizae", "hebrew_name": "זיגנה בריזאה", "english_name": "" },
    { "scientific_name": "Zekelita ravalis", "hebrew_name": "זקליטה רבליס", "english_name": "" },
    { "scientific_name": "Zethes insularis", "hebrew_name": "זתס אינסולריס", "english_name": "" },
    { "scientific_name": "Tegostoma baphialis", "hebrew_name": "טגוסטומה בפילס", "english_name": "" },
    { "scientific_name": "Teinoptera gafsana", "hebrew_name": "טיינופטרה גפסנה", "english_name": "" },
    { "scientific_name": "Trichophaga bipartitella", "hebrew_name": "טריכופגה ביפרטיטלה", "english_name": "" },
    { "scientific_name": "Euproctis fasciata", "hebrew_name": "יופרוקטיס סוזנה", "english_name": "" },
    { "scientific_name": "Choreutis aegyptiaca", "hebrew_name": "כוראוטיס אגיפטיאקה", "english_name": "" },
    { "scientific_name": "Choreutis sexfasciella", "hebrew_name": "כוראוטיס סקספסיאלה", "english_name": "" },
    { "scientific_name": "Chamaesphecia chalciformis", "hebrew_name": "כמספציה חלקיפורמיס", "english_name": "" },
    { "scientific_name": "Chamaesphecia masariformis", "hebrew_name": "כמספציה מסריפורמיס", "english_name": "" },
    { "scientific_name": "Charissa subtaurica", "hebrew_name": "כריסה סובטאוריקה", "english_name": "" },
    { "scientific_name": "Leucochlaena jordana", "hebrew_name": "לאוקוכלאנה ירדנית", "english_name": "" },
    { "scientific_name": "Leucochlaena muscosa", "hebrew_name": "לאוקוכלאנה מוסקוסה", "english_name": "" },
    { "scientific_name": "Loryma egregialis", "hebrew_name": "Pied Tabby", "english_name": "" },
    { "scientific_name": "Lithostege palaestinensis", "hebrew_name": "ליתוסטגה פלשתינאית", "english_name": "" },
    { "scientific_name": "Lithophane lapidea", "hebrew_name": "ליתופנה לפידאה", "english_name": "" },
    { "scientific_name": "Lasiocampa josua", "hebrew_name": "טוואי יהושע", "english_name": "" },
    { "scientific_name": "Lasiocampa terreni", "hebrew_name": "לסיאוקמפה טרני", "english_name": "" },
    { "scientific_name": "Meganola togatulalis", "hebrew_name": "מגנולה טוגטולליס", "english_name": "" },
    { "scientific_name": "Metachrostis velox", "hebrew_name": "מטאכרוסטיס וולוקס", "english_name": "" },
    { "scientific_name": "Metasia rosealis", "hebrew_name": "מטאסיה רוזאליס", "english_name": "" },
    { "scientific_name": "Mattia callidaria", "hebrew_name": "מטיאה קלידריה", "english_name": "" },
    { "scientific_name": "Microloxia herbaria", "hebrew_name": "מיקרולוקסיה הרבריה", "english_name": "" },
    { "scientific_name": "Micronola wadicola", "hebrew_name": "מיקרונולה ואדיקולה", "english_name": "" },
    { "scientific_name": "Micropterix elegans", "hebrew_name": "מיקרופטריקס אלגנס", "english_name": "" },
    { "scientific_name": "Micropterix berytella", "hebrew_name": "מיקרופטריקס בריטלה", "english_name": "" },
    { "scientific_name": "Mythimna languida", "hebrew_name": "מיתימנה לנגווידה", "english_name": "" },
    { "scientific_name": "Mesophleps corsicella", "hebrew_name": "מסופלפס קורסיקלה", "english_name": "" },
    { "scientific_name": "Merulempista turturella", "hebrew_name": "מרולמפיסטה טורטורלה", "english_name": "" },
    { "scientific_name": "Nola infantula", "hebrew_name": "נולה אינפנטולה", "english_name": "" },
    { "scientific_name": "Neromia pulvereisparsa", "hebrew_name": "נרומיה פולוורייזפרסה", "english_name": "" },
    { "scientific_name": "Sazonia fenusaeformis", "hebrew_name": "סזוניה פנוסאפורמיס", "english_name": "" },
    { "scientific_name": "Stathmopoda auriferella", "hebrew_name": "סטאתמופודה אוריפרלה", "english_name": "" },
    { "scientific_name": "Stilbina hypaenides", "hebrew_name": "סטילבינה היפנידס", "english_name": "" },
    { "scientific_name": "Cybalomia pentadalis", "hebrew_name": "סיבלומיה פנטדליס", "english_name": "" },
    { "scientific_name": "Symmoca signatella", "hebrew_name": "סימוקה סיגנטלה", "english_name": "" },
    { "scientific_name": "Synanthedon stomoxiformis", "hebrew_name": "סיננתדון סטומקסיפורמיס", "english_name": "" },
    { "scientific_name": "Synaphe morbidalis", "hebrew_name": "סינפה מורבידליס", "english_name": "" },
    { "scientific_name": "Scopula minorata", "hebrew_name": "סקופולה מינורטה", "english_name": "" },
    { "scientific_name": "Scythris flabella", "hebrew_name": "סקיתריס פלבלה", "english_name": "" },
    { "scientific_name": "Chlorissa etruscaria", "hebrew_name": "פאיוגרמה אטרוסקריה", "english_name": "" },
    { "scientific_name": "Phaiogramma faustinata", "hebrew_name": "פאיוגרמה פאוסטנטה", "english_name": "" },
    { "scientific_name": "Phaselia deliciosaria", "hebrew_name": "פאסליה דליסיוסריה", "english_name": "" },
    { "scientific_name": "Polymixis ivanchiki", "hebrew_name": "פולימיקסיס איוונטשיקי", "english_name": "" },
    { "scientific_name": "Polymixis trisignata", "hebrew_name": "פולימיקסיס טריסיגנטה", "english_name": "" },
    { "scientific_name": "Polymixis serpentina", "hebrew_name": "פולימיקסיס סרפנטינה", "english_name": "" },
    { "scientific_name": "Furcula interrupta", "hebrew_name": "דו זיפן הצפצפה", "english_name": "" },
    { "scientific_name": "Pterophorus ischnodactyla", "hebrew_name": "פטרופורוס אישנודקטילוס", "english_name": "" },
    { "scientific_name": "Pyroderces argyrogrammos", "hebrew_name": "פירודרסס ארגירוגרמוס", "english_name": "" },
    { "scientific_name": "Pyropteron jordanicum", "hebrew_name": "פירופטרון ירדני", "english_name": "" },
    { "scientific_name": "Pelochrista labyrinthicana", "hebrew_name": "פלוכריסטה לבירינטיקנה", "english_name": "" },
    { "scientific_name": "Palumbina guerinii", "hebrew_name": "פלומבינה גריני", "english_name": "" },
    { "scientific_name": "Phalonidia contractana", "hebrew_name": "פלונידיה קונטרקטנה", "english_name": "" },
    { "scientific_name": "Plecoptera reflexa", "hebrew_name": "פלקופטרה רפלקסה", "english_name": "" },
    { "scientific_name": "Psorosa tergestella", "hebrew_name": "פסאודואקרובסיס טרסגסטלה", "english_name": "" },
    { "scientific_name": "Pseudopanthera syriacata", "hebrew_name": "פסאודופנתרה סיריאקטה", "english_name": "" },
    { "scientific_name": "Pseudenargia deleta", "hebrew_name": "פסאודנרגיה דלטה", "english_name": "" },
    { "scientific_name": "Pericyma albidentaria", "hebrew_name": "פריסימה אלבידנטריה", "english_name": "" },
    { "scientific_name": "Pericyma squalens", "hebrew_name": "פריסימה סקוואלנס", "english_name": "" },
    { "scientific_name": "Parapoynx affinialis", "hebrew_name": "פרפוינקס אפיניאליס", "english_name": "" },
    { "scientific_name": "Cerocala sana", "hebrew_name": "צרוקלה סנה", "english_name": "" },
    { "scientific_name": "Cornifrons ulceratalis", "hebrew_name": "קורניפרונס אולצרטליס", "english_name": "" },
    { "scientific_name": "Catocala eutychea", "hebrew_name": "קטוקלה אוטיכאה", "english_name": "" },
    { "scientific_name": "Catarhoe hortulanaria", "hebrew_name": "קטרואה הורטולנריה", "english_name": "" },
    { "scientific_name": "Catarhoe mosulensis", "hebrew_name": "קטרואה מוסולנסיס", "english_name": "" },
    { "scientific_name": "Cleonymia chabordis", "hebrew_name": "קלאונימיה חבורדיס", "english_name": "" },
    { "scientific_name": "Clytie infrequens", "hebrew_name": "קליטיה אינפרקוונס", "english_name": "" },
    { "scientific_name": "Clytie syriaca", "hebrew_name": "קליטיה סוריאקה", "english_name": "" },
    { "scientific_name": "Clepsis burgasiensis", "hebrew_name": "קלפסיס בורגסיאנסס", "english_name": "" },
    { "scientific_name": "Nebula salicata", "hebrew_name": "קנוטפריה אבולוטריה", "english_name": "" },
    { "scientific_name": "Casama innotata", "hebrew_name": "טוואית הינבוט", "english_name": "" },
    { "scientific_name": "Xestia palaestinensis", "hebrew_name": "קססטיה פלשתינאית", "english_name": "" },
    { "scientific_name": "Crocallis tusciaria", "hebrew_name": "קרוקליס טוסקיאריה", "english_name": "" },
    { "scientific_name": "Cryptoblabes gnidiella", "hebrew_name": "קריפטובלבאס גנידיאלה", "english_name": "" },
    { "scientific_name": "Rhabdophera arefacta", "hebrew_name": "רבדוסטרופיה ארפקטה", "english_name": "" },
    { "scientific_name": "Rhodostrophia tabidaria", "hebrew_name": "רודוסטרופיה דיסקופונקטטה", "english_name": "" },
    { "scientific_name": "Reisserita latiusculella", "hebrew_name": "רייזרריטה לטיוסקוללה", "english_name": "" },
    { "scientific_name": "Theresimima ampellophaga", "hebrew_name": "תרסימימה אמפלופגה", "english_name": "" }
  ]
};

// הופך את האובייקט הענק למערך שטוח בדיוק כמו שהקומפוננטה מצפה לקבל
export const speciesMap: SpeciesInfo[] = Object.entries(rawSpeciesMap).flatMap(
  ([category, entries]) =>
    entries.map((entry) => ({
      Scientific_Name: entry.scientific_name,
      Category: category,
      Hebrew_Name: entry.hebrew_name,
      English_Name: entry.english_name,
    }))
);



